language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

branches:
  only:
    - master

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - mkdir -p build/logs
  - mkdir -p build/docs
  - chmod u+x .travis_shell_after_success.sh
  - pear channel-discover pear.phpdoc.org 
  - pear install phpdoc/phpDocumentor 

script:
  - phpunit
  - phpunit --coverage-clover build/logs/clover.xml
  - phpdoc run -d $TRAVIS_BUILD_DIR/src/ -t $TRAVIS_BUILD_DIR/build/docs

after_script:
  - php vendor/bin/coveralls -v
  - bash .travis_shell_after_success.sh

env:
  global:
    secure: oUCQF9eKPZ64L0ER82o5+fI2SUkbqMpQy2DNt/1osyOgveR2TfjOrqARUvTEQqwM7fT3sl6y+5s4+PRPsBuAYIb8RWjPyJtfDc6WTnynrLhkppKjO+wL5GYlbMDQuvx7SkGJXeysXUKeadqb38samRAS4uL7/Bu+VREdcQ6VyLnc4WnUNd7WFHg+5GMEOgvRxQsPSUZQ5wLWAbkijG/FnSUwKNSJfbXOXsW3AThWfBWuIYyhutb4YnhTOLEINq6ZkbUCxuy9qjDIjBEKxWW8cqJH3OJSChzohV5Amzws3rvsyfFrBX6yYNFK19zViqmCVhzfUey1WeapV3yoe3kMA0dci8C8Vr3pYwh5kYvGb6DuIp8n2/Al3aHrTEuzTJ71iCS2L1mApegzonJfHbq3bwkpe23sW1g6WVC4L51lZT9aSrNPcS/fsvBlGWPOAWkpRXWMP7PJ+Dy2QZb7WfksK504uoMlZ47GwzTn6ZBKay+RhZuaFIG+7epZHsHp7uszOhB5b2pMHQ1wVUTs24VW7J2vCCRmW5E4F7rbNB/93E5BTTdH3SAzMSu8u11C6SDCrBAK0+8ARPIcnoB8MUjXko7ZAjA5YSvV+Uvpgueu+T3CEZdBvr6st8KK8Ke6Xhfy5AqtBI9FBlBpxxEOBglgxW/Urabp9hQQ2SItn85lpzE=
